# Generated by Django 4.1.1 on 2022-09-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_tag_alter_book_price_alter_customer_age_order_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(to='bookstore.tag'),
        ),
    ]
